version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - npm run test
  post_build:
    commands:
      - aws ec2 run-instances --image-id ami-0851b76e8b1bce90b --count 1 --instance-type t2.medium --key-name ami-docker --security-groups launch-wizard-3 --tag-specifications "ResourceType=instance,Tags=[{Key=BuildKey,Value=One}]" --user-data file:///scripts/installCodeDeployAgent.sh
      - echo Build completed on `date`
artifacts:
  files:
    - app.js
    - package.json
    - scripts/install_dependencies.sh
    - scripts/start_server.sh
    - scripts/stop_server.sh
    - appspec.yml
